import os
import pandas as pd
import numpy as np
import re
import subprocess
import glob
import shutil

from snakemake.utils import min_version

__AUTHOR__ = "Robin Tang"
__EMAIL__ = "rbio_tang@foxmail.com"

##### set minimum snakemake version #####
min_version("7.32.4")

##### set default params #####
configfile: "workflow/config/config.yaml"

#### include rules ####
include: "rules/common.smk"
include: "rules/preprocess.smk"
include: "rules/hostRemove.smk"
include: "rules/readsClassify.smk"
include: "rules/getMitogenome.smk"
include: "rules/contigsAssemble.smk"
include: "rules/genePrediction.smk"
include: "rules/readsAnnotation.smk"
include: "rules/contigsBinning.smk"
include: "rules/binsRefine.smk"
include: "rules/binsClassify.smk"
include: "rules/binsAnnotation.smk"


rule all:
    input:
        get_report(),
    message:
        """
        Start to run the pipeline. --------------------------------------------------
        """
    log:
        "logs/all.log"
