from snakemake.utils import min_version
import os

__AUTHOR__ = "Robin Tang"
__EMAIL__ = "rbio_tang@foxmail.com"

##### set minimum snakemake version #####
min_version("7.32.4")

##### set default params #####
configfile: "workflow/config/config.yaml"

#### include rules ####
include: "rules/preprocess.smk"
include: "rules/removeHost.smk"
include: "rules/readsClassify.smk"
include: "rules/getMitogenome.smk"

rule all:
    input:
        "logs/01_check_run.log",
        config["root"] + "/" + config["folder"]["reads_classify"] + "/bracken_report.txt",
        expand(config["root"] + "/" + config["folder"]["mitogenome"] + "/{individual}/{individual}.result",individual=get_run_individual())
    message:
        """
        Start to run the pipeline. --------------------------------------------------
        """
    log:
        "logs/all.log"
