root: /home/user002/fish
db_root: /home/user002/database
db:
    kraken2: k2_pluspf_20231009_db
    humann_chocophlan: humann3_db/chocophlan-v31
    humann_uniref: humann3_db/uniref
    humann_utility_mapping: humann3_db/utility_mapping
    metaphlan: metaphlan_databases
envs: workflow/config/envs
scripts: workflow/scripts
meta:
    sampleList: workflow/config/sampleList.csv
folder:
    logs: logs
    reports: reports
    index: ref_db
    data: 00_cleandata
    rm_host: 01_remove_host
    reads_classify: 02_kraken2
    mitogenome: 03_host_mitogenome
    assemble_contigs: 04_megahit
    gene_prediction: 05_prodigal
    reads_anno_humann3: 06_reads_annotation/00_humann3
    reads_anno_rgi: 06_reads_annotation/01_rgi
    reads_anno_dbcan: 06_reads_annotation/02_dbcan
    reads_anno_vfdb: 06_reads_annotation/03_vfdb
    contigs_binning: 07_binning
    bin_refine: 08_bin_refine
    bin_quantify: 09_bin_quantify
    bin_anno_rgi: 10_bin_annotation/01_rgi
    bin_anno_dbcan: 10_bin_annotation/02_dbcan
    bin_anno_vfdb: 10_bin_annotation/03_vfdb
reads_length: 150
co_assemble:
    flag: True
    col: [Site_Group, Species_Group]
