# Workdir
root: /home/user002/fish
# MetaInfo
meta:
    sampleList: workflow/config/sampleList.csv
    reads_length: 150
# Modules: [rm_host, reads_classify, get_mitogenome, assemble_contigs, gene_prediction, reads_anno, co_assemble]
reads_classify:
    enable: True
get_mitogenome:
    enable: True
assemble_contigs:
    enable: True
gene_prediction:
    enable: True
reads_anno:
    huamnn3_enable: False
    rgi_enable: False
    dbcan_enable: False
    vfdb_enable: False
co_assemble:
    enable: True
    col: [Site_Group, Species_Group]
    min_ctg_len: 1000
contigs_binning:
    enable: True
bins_dereplicate:
    enable: False
    anno_level: strain
bins_classify:
    enable: True
bins_recall:
    enable: True
    other_mags_list: [human_gut_v2.02, mouse_gut_v1.0, non_model_fish_gut_v2.0, zebrafish_fecal_v1.0]
bins_anno:
    prokka_enable: False
    rgi_enable: True
    dbcan_enable: True
    vfdb_enable: True
    eggnog_enable: True
# Database
db_root: /home/user002/database
db:
    kraken2: kraken2_pluspf_20231009_db
    humann_chocophlan: humann3_20231017_db/chocophlan-v31
    humann_uniref: humann3_20231017_db/uniref
    humann_utility_mapping: humann3_20231017_db/utility_mapping
    metaphlan: metaphlan_20231214_db
    vfdb: vf_20230915_db
    rgi: card_20231214_db
    dbcan: dbcan_20231214_db
    eggnog: eggnog_20240116_db
    checkm: checkm_20150116_db
    gtdbtk: gtdbtk_20231214_db
    taxonkit: taxonkit_20240108_db
    mag_db: download_MAGs_20240322_db
# Folder
envs: workflow/config/envs
scripts: workflow/scripts
folder:
    logs: logs
    reports: reports
    index: ref_db
    data: 00_cleandata
    rm_host: 01_remove_host
    reads_classify: 02_kraken2
    mitogenome: 03_host_mitogenome
    mitotree: 03_mitotree
    assemble_contigs: 04_megahit
    gene_prediction: 05_prodigal
    reads_anno_humann3: 06_reads_annotation/00_humann3
    reads_gene_quant: 06_reads_annotation/01_gene_quant
    reads_anno_rgi: 06_reads_annotation/02_rgi
    reads_anno_dbcan: 06_reads_annotation/03_dbcan
    reads_anno_vfdb: 06_reads_annotation/04_vfdb
    contigs_binning: 07_binning
    bins_refine: 08_bin_refine
    bins_dereplication: 09_dereplication
    bins_classify: 10_bin_classify
    bins_recall: 10_bin_recall
    bins_anno_prokka: 11_bin_annotation/00_prokka
    bins_gene_quant: 11_bin_annotation/01_gene_quant
    bins_anno_rgi: 11_bin_annotation/02_rgi
    bins_anno_dbcan: 11_bin_annotation/03_dbcan
    bins_anno_vfdb: 11_bin_annotation/04_vfdb
    bins_anno_eggnog: 11_bin_annotation/05_eggnog
