root: /home/user002/fish
db_root: /home/user002/database
db:
    kraken2: kraken2_20230803_db
    humann_chocophlan: humann3_db/chocophlan-v31
    humann_uniref: humann3_db/uniref
    humann_utility_mapping: humann3_db/utility_mapping
envs: workflow/config/envs
meta:
    sampleList: workflow/config/sampleList.csv
folder:
    index: ref_db
    data: 00_cleandata
    rm_host: 01_remove_host
    kraken2: 02_kraken2
reads_length: 150